[build]
  publish = "dist/catalog-app/browser"
  command = "npm run build"

[[redirects]]
  from = "/products/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
